export { Home } from "./Home/home";
export { Login } from "./Authentication/login";
export { SignUp } from "./Authentication/signup";
export { LikePage } from "./Like/like";
export { HistoryPage } from "./History/history";
export { WatchLater } from "./WatchLater/watch-later";
export { SinglePlaylist } from "./SinglePlaylist/single-playlist";
export { SingleVideo } from "./SingleVideo/single-video";
export { Playlist } from "./Playlist/playlist";
